name: Auto-Tag Live Deployments

concurrency:
  group: ${{ github.workflow }}-live
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  create_next_live_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # We need to fetch all tags to find the highest one
      with:
        fetch-depth: 0

    - uses: ./.github/actions/pantheon-auto-tag
      with:
        target_env: live

    - uses: ./.github/actions/wait-for-deployment
      with:
        target_env: live
        pantheon_site_machine_name: office-artifacts
